export enum TRPCErrorEnum {
  BAD_REQUEST = "BAD_REQUEST", // 400
  UNAUTHORIZED = "UNAUTHORIZED", // 401 should be called UNAUTHENTICATED
  FORBIDDEN = "FORBIDDEN", // 403
  NOT_FOUND = "NOT_FOUND", // 404
  METHOD_NOT_SUPPORTED = "METHOD_NOT_SUPPORTED", // 405
  TIMEOUT = "TIMEOUT", // 408
  CONFLICT = "CONFLICT", // 409
  PRECONDITION_FAILED = "PRECONDITION_FAILED", // 412
  PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE", // 413
  UNSUPPORTED_MEDIA_TYPE = "UNSUPPORTED_MEDIA_TYPE", // 415
  UNPROCESSABLE_CONTENT = "UNPROCESSABLE_CONTENT", // 422
  TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS", // 429
  CLIENT_CLOSED_REQUEST = "CLIENT_CLOSED_REQUEST", // 499
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR", // 500
  NOT_IMPLEMENTED = "NOT_IMPLEMENTED", // 501
  BAD_GATEWAY = "BAD_GATEWAY", // 502
  SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE", // 503
  GATEWAY_TIMEOUT = "GATEWAY_TIMEOUT", // 504
}

export const trpcUserErrors = [
  TRPCErrorEnum.BAD_REQUEST,
  TRPCErrorEnum.UNAUTHORIZED,
  TRPCErrorEnum.FORBIDDEN,
  TRPCErrorEnum.NOT_FOUND,
  TRPCErrorEnum.CONFLICT,
]

export const trpcClientErrors = [
  TRPCErrorEnum.METHOD_NOT_SUPPORTED,
  TRPCErrorEnum.TIMEOUT,
  TRPCErrorEnum.PRECONDITION_FAILED,
  TRPCErrorEnum.PAYLOAD_TOO_LARGE,
  TRPCErrorEnum.UNSUPPORTED_MEDIA_TYPE,
  TRPCErrorEnum.UNPROCESSABLE_CONTENT,
  TRPCErrorEnum.TOO_MANY_REQUESTS,
  TRPCErrorEnum.CLIENT_CLOSED_REQUEST,
]

export const trpcServerErrors = [
  TRPCErrorEnum.INTERNAL_SERVER_ERROR,
  TRPCErrorEnum.NOT_IMPLEMENTED,
  TRPCErrorEnum.BAD_GATEWAY,
  TRPCErrorEnum.SERVICE_UNAVAILABLE,
  TRPCErrorEnum.GATEWAY_TIMEOUT,
]
